/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class EC_Constants {
    public static final String subscriptionMilestone = 'Subscription ';
    public static final String deliveryMilestone = 'Milestone - Product Delivery';
    public static final String openStatus = 'Open';
    public static final String closedWonStatus = 'Closed Won';
    public static final String closedLostStatus = 'Closed Lost';
    public static final String notInvoiced ='Not Invoiced';
}